#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:nil broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:nil e:nil email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:nil title:nil toc:nil todo:t |:t
#+TITLE: First
#+DATE: <2019-05-01 Wed>
#+AUTHOR: Khinshan Khan
#+EMAIL: khinshan.khan@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.2 (Org mode 9.1.9)

#title: First Post!
#date: 2019-05-01
#descr: The first of many posts. Details about the website here.
#tags: [intro, volatile]

*
** Mini Prelude
Well I guess to start with, it may be important to note that this post was actually backdated a little. This backdating doesn't have malicious intents like [[https://www.lumendatabase.org/blog_entries/800][some companies do]], it's meant to keep this post in the beginning as it outlines how my website will work.

** Details
To start with, posts will usually have the followiing meta data: title, date, descr, and tags. The rest of the meta isn't particularly relevant, but available regardless. Title and date should be rater self-explanatory. Currently description is rather useless. Ergo, let's zero in on the most important meta data: tags. Next paragraph to isolate this information for the readers!

Tags are probably the most important and possibly most convoluted mechanism in this site for the users. To start with, every post will have at least one tag (I set up the python "backend" to yell at me if I ever forget). These tags will attempt to be descriptive of the post. But in addition, I'm going idea that tags will show the "status of the post". That is to say, a tag like "discussion" will mean the post has a comment section includes (once I implement comments, you'll see that on almost every post). Here's a mini outline of what I'm going for:

*** Key Tag System
- "volatile": means that the post is subject to editing (well, all posts are, but this tag means the content can change. Others would change for small typos or errors... unless I misunderstand and convey incorrect information, in which case I'll make it apparent using strikethroughs or something.)
- "discussion": some sort of comment interface is active for the post
- "discretion": I wouldn't recommend reading this in front of a younger audience (these may pop up in literature that I choose to discuss).
- "thoughts": my 2 cents about a topic, probably opinionated, so no need to yell at me.
- "analysis": a logical breakdown and discussion of implications for certain topics (usually technology).
- "lesson": a post designed to teach rather than discuss.
- "notes": the post is either derived from my classnotes or personal life.

** About this Site
Now some of you may be wondering how in the world this site works, the source code for this is available on [[https://github.com/kkhan01/kkhan01.github.io][here on github]]. Currently, I'm statically generating this site and hosting it entirely using github pages (makes you really appreciate this [[https://khinshankhan.com/404][unique 404]]). If I ever shift to a dynamic site or use netlify or something, fret not for the code will continue to be available here.

Currently, I'm using [[https://pythonhosted.org/Frozen-Flask/][Frozen-Flask]] to convert a flask app into static content. Along with a bunch of scripts as found [[https://github.com/kkhan01/kkhan01.github.io/tree/master/_flask][here]], I'm able to use org files to write my posts and deploy almost seamlessly. Obviously I wouldn't recommend this setup to everyone, since it requires you to actually go through and understand every piece of code, since you may need to edit an obscure snippet to get a minor change. If enough people ask, and maybe a little team assembles, I'll happily try to create a standalone repository which anyone can fork and easily use as a template (I'm okay with anyone forking my current repository as long as they credit me somewhere and understand they won't be able to use it out-of-the-box).

** Credit
I feel strongly about giving credit where it's due. The following is a list that contributed to the making of this site:
- [[https://github.com/larstvei][Lars Tveito's]] melpa package [[https://github.com/larstvei/ox-gfm][ox-gfm]]: I repurposed this github flavored markdown exporter to suit flask's markdown (I haven't made that changed package public yet). I also made a little [[https://raw.githubusercontent.com/kkhan01/elisp/master/org2md.el][script]] to export org files in a directory to markdown.
- [[https://lukemcdonald.com/][Luke McDonald's]] image [[https://www.toptal.com/designers/subtlepatterns/debut-light/][Debut Light]]: really awesome subtle pattern to ease the contrast. Using it as the background in my site right now.
- [[https://github.com/insomnux][insomnux's]] flaskblog: this was really just my starting point. Thanks to this, I found Frozen-Flask and was able to statically create my site instead of either buying a server or forgoing DRY development and copy pasting code like the navbar and footer (well technically... the static build generated... at least the templates are powerful and ease my workload).
- [[https://pixabay.com/users/pexels-2286921/][Pexels']] [[https://pixabay.com/photos/constellation-cosmos-dark-1851128/][constellation]]: cool image, using it as my background for this site as of now.


** Final Note
Finally, I'll try to eventually maintain /at least/ weekly posts (hopefully I'll be posting more than once a week), but I'm not sure how long it'll take me to reach that level. For now, I'll be posting whenever is convenient.
